# Generated by Django 5.0.7 on 2025-05-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questfeedback',
            name='para',
            field=models.CharField(choices=[('2', 'Со второй половинкой'), ('1', 'Один/Одна'), ('0', 'Не получится придти')], default='1', max_length=1),
        ),
    ]
